### PR TITLE
added change to schema to allow you to run devel charts

### PR DESCRIPTION
**Pull request by scotty-c**
This is a fix for #37. 
I have just updated the schema to have a bool for the devel flag. 
Then made the adjustments to the `InstallArguments struct` to add devel and the same with the `cmd.Args`

### CODE REVIEW

**Comment by jeremyrickard** [comment]
Hey @scotty-c you'll need to update the unit tests on this, we check the schema.

**Comment by carolynvs** [comment]
@scotty-c Oops, looks like the expected test value is a bit out of date. 

Here you can see the test run, click on the red "unit test" section and you can see the output:
https://dev.azure.com/deislabs/porter/_build/results?buildId=1879

**Comment by scotty-c** [comment]
@carolynvs I have updated the test schema now to match the changes that I made to the actual schema. `make test-unit` is passing now when I run it locally.

**Pull request merged**
